### PR TITLE
44/fix message styling

### LINKED ISSUE #44: Fix chatbox message styling issues
### Problem
1. When including images they have no constraints and overflow the message box.
2. ordered lists (`ol`) do not have the same left padding as unordered lists (`ul`)
3. Code is not highlighted

### Fix
1. Add  `max-width: 100%` property to `img` in chatbox
2. Add `padding-inline-start: 20px` to `ol` and `ul`
3. Add code highlighting

### PR DESCRIPTION
**Pull request by spaenleh**
This PR fixes the image overflow bug and improves the styling of the code blocks which now support syntax highlighting !

chat_before_after

> @pyphilia Sorry for a lot of files changed, they are mostly prettier doing his thing with the new import order plugin.

closes #44

### CODE REVIEW

File: src/components/MessageBody.tsx [hunk 1]
```diff
@@ -1,11 +1,32 @@
...
+import ReactMarkdown from 'react-markdown';
+import { CodeProps } from 'react-markdown/lib/ast-to-react';
+
 import { makeStyles } from '@material-ui/core/styles';
 
 const useStyles = makeStyles((theme) => ({
   messageParagraphs: {
+    '& .prism-code': {
+      fontFamily:
+        'ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace',
```
Comment (dialexo) [inline src/components/MessageBody.tsx:16]: Are those fonts available on any system? Or do we import them through e.g. Google Fonts? Similar below

File: src/components/MessageBody.tsx [hunk 2]
```diff
@@ -1,11 +1,32 @@
...
+      // margin: theme.spacing(1),
+      backgroundColor: 'transparent !important',
```
Comment (dialexo) [inline src/components/MessageBody.tsx:18]: Is the use of `!important` unavoidable here?

File: src/components/MessageBody.tsx [hunk 3]
```diff
@@ -46,20 +73,78 @@ const useStyles = makeStyles((theme) => ({
...
   messageBody: string;
 };
 
+const renderCode = ({
+  inline,
+  className: classNameInit,
+  children: codeContent,
+  ...props
+}: CodeProps): ReactElement => {
+  const match = /language-(\w+)/.exec(classNameInit || '');
```
Comment (dialexo) [inline src/components/MessageBody.tsx:92]: Consider using [`String.prototype.match`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) as [RegExp objects are stateful](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec). Obviously in this case this doesn't change anything, but this would clarify the intention for future maintenance.

File: src/components/MessageBody.tsx [hunk 4]
```diff
@@ -46,20 +73,78 @@ const useStyles = makeStyles((theme) => ({
...
+  return !inline && match ? (
+    <Highlight
+      {...defaultProps}
+      theme={vsLight}
+      code={String(codeContent).replace(/\n$/, '')}
+      language={match[1] as Language}
```
Comment (dialexo) [inline src/components/MessageBody.tsx:98]: Are we guaranteed that `match[1]` exists? What if match is null, and could the array have less than 2 elements?

**Review by dialexo — CHANGES_REQUESTED** [review]
Nice! Thanks for this PR 👍 I left a few comments regarding import order and various nitpicks

**Comment by dialexo** [comment]
> chat_before_after

By the way from the image it seems the code blocks used to have a monospace font, while they now have a regular font?

File: src/components/MessageBody.tsx (hunk 3 above)
Comment (spaenleh) [reply src/components/MessageBody.tsx:92]: Ok thank you !

File: src/components/MessageBody.tsx (hunk 4 above)
Comment (spaenleh) [reply src/components/MessageBody.tsx:98]: Yes, when the class defining the language is present and we have a match, it will contain at index 1 the matched language.

**Comment by spaenleh** [comment]
Updated code now correctly renders monospace code:
Screenshot 2022-07-01 at 17 28 12

File: src/components/MessageBody.tsx (hunk 1 above)
Comment (dialexo) [reply src/components/MessageBody.tsx]: It seems that by default `ui-monospace` [is not widely supported](https://caniuse.com/extended-system-fonts), while `SF Mono` and `Menlo` are Apple-specific, `Consolas` is Microsoft-specific and `Liberation Mono` is Red Hat Linux specific (though it is available for other systems as well).

So it really depends on how consistent you want the font experience to be. If having the exact same styling on every platform is a concern, then you should ship the font (e.g. using Google Font or a custom CSS import). If using any monospace font is the only requirement, then IMO it is fine to live it as is (the specific system of the user will pick the first available font on the machine, and default to the system's `monospace` font).

**Review by dialexo — APPROVED** [review]

File: package.json [hunk 5]
```diff
@@ -50,15 +50,17 @@
   },
   "dependencies": {
     "@graasp/translations": "github:graasp/graasp-translations.git",
-    "@graasp/ui": "github:graasp/graasp-ui",
+    "@graasp/ui": "github:graasp/graasp-ui#134/optionalDep",
```
Comment (pyphilia) [inline package.json:53]: This has been merged ;)

File: src/components/MessageBody.tsx [hunk 6]
```diff
@@ -1,22 +1,41 @@
...
+import { CodeProps } from 'react-markdown/lib/ast-to-react';
+
 import { makeStyles } from '@material-ui/core/styles';
 
 const useStyles = makeStyles((theme) => ({
   messageParagraphs: {
-    // set margins for all elements
+    fontFamily: theme.typography.fontFamily,
+    '& :last-child': {
+      // marginBottom: 0,
```
Comment (pyphilia) [inline src/components/MessageBody.tsx:16]: Remove?

**Review by pyphilia — APPROVED** [review]
