### PR TITLE
Fix overflow text

### LINKED ISSUE #40: Fix text overflowing the box

### PR DESCRIPTION
**Pull request by spaenleh**
This PR fixes the overflow bug on the messages and adds markdown support to
messages.

Preview of link not overflowing:
Screenshot 2022-05-18 at 18 33 45

And Preview of markdown comment:
Screenshot 2022-05-18 at 18 34 03

Styles are crafted manually, so some tweaking may be required, feedback is appreciated 😊

closes #40

### CODE REVIEW

File: example/src/components/ChatboxTest.tsx [hunk 1]
```diff
@@ -18,118 +18,127 @@ import {
...
+        margin: theme.spacing(2, 0) + '!important',
+      },
+    },
+    textInputControl: {
+      width: '100%',
+    },
+    chatInputBox: {
+      backgroundColor: 'white',
+      // borderRadius: '8px',
+      // border: 'solid red 2px',
```
Comment (pyphilia) [inline example/src/components/ChatboxTest.tsx:59]: remove?

File: example/src/components/ChatboxTest.tsx [hunk 2]
```diff
@@ -18,118 +18,127 @@ import {
...
+  }));
+
+  const classes = useStyles();
+
   // adapt the width of the chatbox to simulate the width used on Graasp
-  const onCheckPanelWidth = (e: React.ChangeEvent<HTMLInputElement>) => {
-    if (Number(e.target.value) === 0) {
-      setTestWidth(GRAASP_PANEL_WIDTH);
+  const onChangePanelWidth = (_: unknown, newValue: number | number[]) => {
+    if (typeof newValue == 'number') {
```
Comment (pyphilia) [inline example/src/components/ChatboxTest.tsx:67]: `Number.isInteger()`? or similar

File: src/components/MessageBody.tsx [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+import remarkBreaks from 'remark-breaks';
+import { makeStyles } from '@material-ui/core/styles';
+
+const useStyles = makeStyles(() => ({
+  messageParagraphs: {
+    // set margins for all elements
+    '& *': {
+      marginBlockStart: '4px',
+      marginBlockEnd: '4px',
+      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
```
Comment (pyphilia) [inline src/components/MessageBody.tsx:13]: Factor out the font family.

File: src/components/MessageBody.tsx [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+      fontSize: '1rem',
+      fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
+    },
+    '& ul': {
+      // define offset for list
+      paddingInlineStart: '20px',
+    },
+    '& code': {
+      padding: '0.2em 0.4em',
+      borderRadius: '6px',
```
Comment (pyphilia) [inline src/components/MessageBody.tsx:26]: `theme.spacing`? Anywhere you think it fits here!

**Review by pyphilia — CHANGES_REQUESTED** [review]
LGTM 🐘  I've added minor suggestions.

File: example/src/components/ChatboxTest.tsx (hunk 2 above)
Comment (spaenleh) [reply example/src/components/ChatboxTest.tsx:67]: I was just trying to narrow the type to `number` so that TS would not complain. In the current setup i will always receive only `number` types for the slider but i had to put the function argument like this to that it would not complain... What do you think @pyphilia ?

**Review by pyphilia — APPROVED** [review]
🖌️
