### PR TITLE
fix: adapt types to use sdk instead of query-client

### LINKED ISSUE #73: Update types

### PR DESCRIPTION
**Pull request by spaenleh**
This PR removes the usage of types exported from query-client and instead uses the ones provided by `@graasp/sdk/frontend`.

Update yarn to 3.4.1

✅ Ready to merge ! ~~Needs to be merged after https://github.com/graasp/graasp-sdk/pull/75 and before https://github.com/graasp/graasp-builder/pull/440~~

closes #73

### CODE REVIEW

**Comment by spaenleh** [comment]
Need to fix tests.

File: example/src/components/ChatboxWrapper.tsx [hunk 1]
```diff
@@ -35,23 +36,14 @@ const ChatboxWrapper: FC<Props> = ({
...
-    mutate: editMessage,
-  }: { mutate: (message: PartialChatMessage) => void } = useMutation(
-    MUTATION_KEYS.PATCH_ITEM_CHAT_MESSAGE,
-  );
+  const { mutate: sendMessage }: { mutate: SendMessageFunctionType } =
+    useMutation(MUTATION_KEYS.POST_ITEM_CHAT_MESSAGE);
+  const { mutate: deleteMessage }: { mutate: DeleteMessageFunctionType } =
+    useMutation(MUTATION_KEYS.DELETE_ITEM_CHAT_MESSAGE);
+  const { mutate: editMessage }: { mutate: EditMessageFunctionType } =
+    useMutation(MUTATION_KEYS.PATCH_ITEM_CHAT_MESSAGE);
```
Comment (pyphilia) [inline example/src/components/ChatboxWrapper.tsx:46]: If you are really motivated, we should import `usePostItemChanMesssage = useMutation(MUTATION_KEYS.POST_ITEM_CHAT_MESSAGE);` directly from query-client so we don't need to type the mutation each time.

File: src/components/Chatbox/Chatbox.tsx [hunk 2]
```diff
@@ -42,15 +43,15 @@ type Props = {
   sendMessageBoxId?: string;
   messages?: ChatMessageList;
   isLoading?: boolean;
-  sendMessageFunction?: (message: PartialNewChatMessage) => void;
-  deleteMessageFunction?: (message: PartialChatMessage) => void;
-  editMessageFunction?: (message: PartialChatMessage) => void;
+  sendMessageFunction?: SendMessageFunctionType;
+  deleteMessageFunction?: DeleteMessageFunctionType;
```
Comment (pyphilia) [inline src/components/Chatbox/Chatbox.tsx:47]: And here I don't know if it would be possible to do `typeof useDeleteMessage`?

**Review by pyphilia — COMMENTED** [review]
LGTM 🌻

**Review by pyphilia — APPROVED** [review]

File: example/src/components/ChatboxWrapper.tsx (hunk 1 above)
Comment (spaenleh) [reply example/src/components/ChatboxWrapper.tsx:46]: Yes this would be tackled in https://github.com/graasp/graasp-query-client/issues/239

File: src/components/Chatbox/Chatbox.tsx (hunk 2 above)
Comment (spaenleh) [reply src/components/Chatbox/Chatbox.tsx:47]: Yes it would be possible and better to derive the type of the function from the hook itself !
